[muqueue]

  [muqueue.async_subsystem]
    # NI
    num_workers = 2

  [muqueue.scheduler]
    # NI
    num_workers = 4
    # NI
    queue_capacity = 1000

[muflow]

  [muflow.dynamic_loader]
    # NI
    function_library_path = ""

  [muflow.sparse_mem]
    # NI
    detector_threshold = 0.8

[muroute]

  # NI
  serial_interface = ""
  # NI
  default_port = ""
 
  [muroute.telemetry]
    # telemetry is disabled if both @with_local_log and @with_network
    # are set to false or commented out - this is the default behaviour
    with_local_log = true
    with_network = true

    # setting @with_crc to true adds a slight overhead, enabled by default
    #with_crc = false

    # if @network_interface is not set, then telemetry will try to use heuristic
    # to determine one - in this case www.google.com must be resolvable
    #network_interface = "wlan0"

    # 1. if @log_directory_path is not set (="" or commented out) then the logs
    # will be collected in a directory from where the application is run
    # 2. @log_directory_path must point to an existing directory
    #log_directory_path = "/home/nvidia/work/telemetry_logs"
    
    # by default, telemetry uses 7777 port number
    #telemetry_port = 7777
